"******************************"
"                              "
"       MyVimRC                "
"              - by ccorazza   "
"                              "
"******************************"

" --- Use Pathogen for Plugins ---

execute pathogen#infect()
filetype plugin indent on
autocmd VimEnter * NERDTree
autocmd BufEnter * NERDTreeMirror

" --- Filetypes ---
autocmd FileType html setlocal shiftwidth=2 tabstop=2 noexpandtab
autocmd FileType python setlocal shiftwidth=2 tabstop=2 noexpandtab
autocmd FileType javascript setlocal shiftwidth=3 tabstop=3 noexpandtab
autocmd FileType c setlocal cindent shiftwidth=4 tabstop=4 noexpandtab


" --- Command completion ---

set wildmenu
set wildmode=list:longest

" --- Pretty Colors ---

syntax on
colorscheme jungle
set background=dark

" --- Syntax ---

set smarttab
" set list listchars=tab:\|\ ,eol:%
set autoindent
set ignorecase

" --- Splits ---
"
"		Shortcuts to switch buffers between splitted tabs : ctrl+ j / k / l / h :
"		Saving strokes from not having to use ctrl-w > j...
"

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" --- Highlights ---

"highlight NotAutorised   ctermfg=darkred ctermbg=lightred
"highlight MyError        ctermbg=darkred

" --- Rollin' & Scratchin'---

set mouse=a
set number
set ruler
set cursorline

" --- What to do with Unsaved Files ---

set confirm


" --- Quit if only NerdTree File left ---

autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()
function! s:CloseIfOnlyNerdTreeLeft()
	if exists("t:NERDTreeBufName")
		if bufwinnr(t:NERDTreeBufName) != -1
			if winnr("$") == 1
				q
			endif
		endif
	endif
endfunction
